package fifthstar;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class BiggerIsGreaterTest {

    private static Stream<Arguments> createParameters() {
        List<String> values = Arrays.asList(
                "imllmmcslslkyoegymoa",
                "fvincndjrurfh",
                "rtglgzzqxnuflitnlyit",
                "mhtvaqofxtyrz",
                "zalqxykemvzzgaka",
                "wjjulziszbqqdcpdnhdo",
                "japjbvjlxzkgietkm",
                "jqczvgqywydkunmjw",
                "ehdegnmorgafrjxvksc",
                "tydwixlwghlmqo",
                "wddnwjneaxbwhwamr",
                "pnimbesirfbivxl",
                "mijamkzpiiniveik",
                "qxtwpdpwexuej",
                "qtcshorwyck",
                "xoojiggdcyjrupr",
                "vcjmvngcdyabcmjz",
                "xildrrhpca",
                "rrcntnbqchsfhvijh",
                "kmotatmrabtcomu",
                "bnfcejmyotvw",
                "dnppdkpywiaxddoqx",
                "tmowsxkrodmkkra",
                "jfkaehlegohwggf",
                "ttylsiegnttymtyx",
                "kyetllczuyibdkwyihrq",
                "xdhqbvlbtmmtshefjf",
                "kpdpzzohihzwgdfzgb",
                "kuywptftapaa",
                "qfqpegznnyludrv",
                "ufwogufbzaboaepslikq",
                "jfejqapjvbdcxtkry",
                "sypjbvatgidyxodd",
                "wdpfyqjcpcn",
                "baabpjckkytudr",
                "uvwurzjyzbhcqmrypraq",
                "kvtwtmqygksbim",
                "ivsjycnooeodwpt",
                "zqyxjnnitzawipqsm",
                "blmrzavodtfzyepz",
                "bmqlhqndacv",
                "phvauobwkrcfwdecsd",
                "vpygyqubqywkndhpzw",
                "yikanhdrjxw",
                "vnpblfxmvwkflqobrk",
                "pserilwzxwyorldsxksl",
                "qymbqaehnyzhfqpqprpl",
                "fcakwzuqlzglnibqmkd",
                "jkscckttaeifiksgkmxx",
                "dkbllravwnhhfjjrce",
                "imzsyrykfvjt",
                "tvogoocldlukwfcajvix",
                "cvnagtypozljpragvlj",
                "hwcmacxvmus",
                "rhrzcpprqccf",
                "clppxvwtaktchqrdif",
                "qwusnlldnolhq",
                "yitveovrja",
                "arciyxaxtvmfgquwb",
                "pzbxvxdjuuvuv",
                "nxfowilpdxwlpt",
                "swzsaynxbytytqtq",
                "qyrogefleeyt",
                "iotjgthvslvmjpcchhuf",
                "knfpyjtzfq",
                "tmtbfayantmwk",
                "asxwzygngwn",
                "rmwiwrurubt",
                "bhmpfwhgqfcqfldlhs",
                "yhbidtewpgp",
                "jwwbeuiklpodvzii",
                "anjhprmkwibe",
                "lpwhqaebmr",
                "dunecynelymcpyonjq",
                "hblfldireuivzekegit",
                "uryygzpwifrricwvge",
                "kzuhaysegaxtwqtvx",
                "kvarmrbpoxxujhvgpw",
                "hanhaggqzdpunkugzmhq",
                "gnwqwsylqeuqr",
                "qzkjbnyvclrkmdtc",
                "argsnaqbquv",
                "obbnlkoaklcx",
                "ojiilqieycsasvqosycu",
                "qhlgiwsmtxbffjsxt",
                "vvrvnmndeogyp",
                "ibeqzyeuvfzb",
                "sajpyegttujxyx",
                "zmdjphzogfldlkgbchnt",
                "tbanvjmwirxx",
                "gmdhdlmopzyvddeqyjja",
                "yxvmvedubzcpd",
                "soygdzhbckfuk",
                "gkbekyrhcwc",
                "wevzqpnqwtpfu",
                "rbobquotbysufwqjeo",
                "bpgqfwoyntuhkvwo",
                "schtabphairewhfmp",
                "rlmrahlisggguykeu",
                "fjtfrmlqvsekq");

        List<String> expected = Arrays.asList("imllmmcslslkyoegyoam",
                "fvincndjrurhf",
                "rtglgzzqxnuflitnlyti",
                "mhtvaqofxtyzr",
                "zalqxykemvzzgkaa",
                "wjjulziszbqqdcpdnhod",
                "japjbvjlxzkgietmk",
                "jqczvgqywydkunmwj",
                "ehdegnmorgafrjxvsck",
                "tydwixlwghlomq",
                "wddnwjneaxbwhwarm",
                "pnimbesirfbixlv",
                "mijamkzpiiniveki",
                "qxtwpdpwexuje",
                "qtcshorwykc",
                "xoojiggdcyjrurp",
                "vcjmvngcdyabcmzj",
                "xildrrpach",
                "rrcntnbqchsfhvjhi",
                "kmotatmrabtcoum",
                "bnfcejmyotwv",
                "dnppdkpywiaxddoxq",
                "tmowsxkrodmkrak",
                "jfkaehlegowfggh",
                "ttylsiegnttymxty",
                "kyetllczuyibdkwyiqhr",
                "xdhqbvlbtmmtshejff",
                "kpdpzzohihzwgdgbfz",
                "kuywptftpaaa",
                "qfqpegznnyludvr",
                "ufwogufbzaboaepsliqk",
                "jfejqapjvbdcxtkyr",
                "sypjbvatgiodddxy",
                "wdpfyqjcpnc",
                "baabpjckkyturd",
                "uvwurzjyzbhcqmryprqa",
                "kvtwtmqygksbmi",
                "ivsjycnooeodwtp",
                "zqyxjnnitzawipsmq",
                "blmrzavodtfzyezp",
                "bmqlhqndavc",
                "phvauobwkrcfwdedcs",
                "vpygyqubqywkndhwpz",
                "yikanhdrwjx",
                "vnpblfxmvwkflqokbr",
                "pserilwzxwyorldsxlks",
                "qymbqaehnyzhfqpqrlpp",
                "fcakwzuqlzglnidbkmq",
                "jkscckttaeifiksgkxmx",
                "dkbllravwnhhfjjrec",
                "imzsyrykfvtj",
                "tvogoocldlukwfcajvxi",
                "cvnagtypozljprajglv",
                "hwcmacxvsmu",
                "rhrzcpprqcfc",
                "clppxvwtaktchqrfdi",
                "qwusnlldnolqh",
                "yitverajov",
                "arciyxaxtvmfgqwbu",
                "pzbxvxdjuuvvu",
                "nxfowilpdxwltp",
                "swzsaynxbytyttqq",
                "qyrogefletey",
                "iotjgthvslvmjpcchufh",
                "knfpyjtzqf",
                "tmtbfayantwkm",
                "asxwzygnngw",
                "rmwiwrurutb",
                "bhmpfwhgqfcqfldlsh",
                "yhbidtewppg",
                "jwwbeuiklpodziiv",
                "anjhprmkwieb",
                "lpwhqaebrm",
                "dunecynelymcpyonqj",
                "hblfldireuivzekegti",
                "uryygzpwifrriecgvw",
                "kzuhaysegaxtwqtxv",
                "kvarmrbpoxxujhvgwp",
                "hanhaggqzdpunkugzmqh",
                "gnwqwsylqeurq",
                "qzkjbnyvclrkmtcd",
                "argsnaqbqvu",
                "obbnlkoaklxc",
                "ojiilqieycsasvqosyuc",
                "qhlgiwsmtxbffjtsx",
                "vvrvnmndeopgy",
                "ibeqzyeuvzbf",
                "sajpyegttujyxx",
                "zmdjphzogfldlkgbchtn",
                "tbanvjmwixrx",
                "gmdhdlmopzyvddeyajjq",
                "yxvmvedubzdcp",
                "soygdzhbckkfu",
                "gkbekyrhwcc",
                "wevzqpnqwtpuf",
                "rbobquotbysufwqjoe",
                "bpgqfwoyntuhkwov",
                "schtabphairewhfpm",
                "rlmrahlisggguykue",
                "fjtfrmlqvseqk");
        return Stream.iterate(0, i -> i + 1)
                .limit(values.size())
                .map(i -> Arguments.of(values.get(i), expected.get(i)));

    }

    @ParameterizedTest
    @MethodSource(value = "createParameters")
    public void testBiggerIsGreater(String value, String expected) {
        String actual = BiggerIsGreater.biggerIsGreater(value);
        assertEquals(expected, actual, () -> "for " + value);
    }

    @Test
    public void test_ehdegnmorgafrjxvksc() {
        String actual = BiggerIsGreater.biggerIsGreater("ehdegnmorgafrjxvksc");
        String expected = "ehdegnmorgafrjxvsck";
        assertEquals(expected, actual);

    }

}
